version: "3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: kl_db
    ports:
      - "5432:5432"
    networks:
      - my_network

  backend:
    build: .
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: kl_db
      DB_PASSWORD: 12345
      DB_PORT: 5432
    ports:
      - "3001:3001"
    networks:
      - my_network
    command: ["sh", "-c", "sleep 10 && npm start"]
    restart: always

networks:
  my_network:
    driver: bridge
